// <auto-generated />
namespace Lap_4_5_6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class updateDBforRegister : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDBforRegister));
        
        string IMigrationMetadata.Id
        {
            get { return "201710070730585_update DB for Register"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
